/**
 * Created by new on 2016/8/2.
 */
const ACTION_PREFIX = 'ROUTER_TEST_';
export const ACTION_LOGIN = ACTION_PREFIX+'ACTION_LOGIN';
export const ACTION_LOGOUT = ACTION_PREFIX+'ACTION_LOGOUT';
export const ACTION_HOME = ACTION_PREFIX+'ACTION_HOME';
export const ACTION_OTHER = ACTION_PREFIX+'ACTION_OTHER';
export const ACTION_MINE = ACTION_PREFIX+'ACTION_MINE';
export const ACTION_APP_START = ACTION_PREFIX+'ACTION_APP_START';
export const ACTION_APP_START_FINISH = ACTION_PREFIX+'ACTION_APP_START_FINISH';
export const ACTION_NEST_FETCH_RESULT = ACTION_PREFIX+'ACTION_NEST_FETCH_RESULT';